// storeActionTypes.js
export const ADD_STORE = 'ADD_STORE';
export const ADD_STORE_SUCCESS = 'ADD_STORE_SUCCESS';
export const ADD_STORE_FAILURE = 'ADD_STORE_FAILURE';

export const GET_STORES = 'GET_STORES';
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS';
export const GET_STORES_FAILURE = 'GET_STORES_FAILURE';

export const UPDATE_STORE = 'UPDATE_STORE';
export const UPDATE_STORE_SUCCESS = 'UPDATE_STORE_SUCCESS';
export const UPDATE_STORE_FAILURE = 'UPDATE_STORE_FAILURE';

export const DELETE_STORE = 'DELETE_STORE';
export const DELETE_STORE_SUCCESS = 'DELETE_STORE_SUCCESS';
export const DELETE_STORE_FAILURE = 'DELETE_STORE_FAILURE';

export const UPDATE_STORE_STATUS = 'UPDATE_STORE_STATUS';
export const UPDATE_STORE_STATUS_SUCCESS = 'UPDATE_STORE_STATUS_SUCCESS';
export const UPDATE_STORE_STATUS_FAILURE = 'UPDATE_STORE_STATUS_FAILURE';
